SELECT PLAYERS.FIRST_NAME , PLAYERS.LAST_NAME , SALARIES.SALARY , Performances.HR , SALARIES.YEAR
FROM PLAYERS
JOIN SALARIES ON PLAYERS.ID = SALARIES.PLAYER_ID
JOIN Performances ON PLAYERS.ID = Performances.PLAYER_ID AND Performances.YEAR = SALARIES.YEAR
ORDER BY PLAYERS.ID ASC , SALARIES.YEAR DESC , Performances.HR DESC , SALARIES.SALARY DESC
